###
# Test build pipeline
###

trigger:
  - develop
pr: none

resources:
  - repo: self

variables:
  acrAddress: 'trekaupunkiymparistoregistry.azurecr.io'
  dockerRegistryServiceConnection: 'acr-trekaupunkiymparisto'
  imageName: 'tre-vuorovaikutusalusta'
  tag: 'test'
  vmImageName: 'ubuntu-latest'

jobs:
  - job: ServerBuild
    displayName: Build server
    dependsOn: []
    pool:
      vmImage: $(vmImageName)
    steps:
      - task: Docker@2
        displayName: Login to ACR
        inputs:
          command: login
          containerRegistry: $(dockerRegistryServiceConnection)
      - script: 'docker pull $(acrAddress)/$(imageName):$(tag)'
        displayName: Pull previous Docker image (for caching)
        # Error occurs here on first build (if the image/tag doesn't yet exist)
        continueOnError: true
      - task: Docker@2
        displayName: Docker build
        inputs:
          command: build
          containerRegistry: $(dockerRegistryServiceConnection)
          repository: '$(imageName)'
          dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
          buildContext: '$(Build.SourcesDirectory)'
          arguments: '--cache-from $(acrAddress)/$(imageName):$(tag)'
          tags: |
            $(tag)
      - task: Docker@2
        displayName: Docker push
        inputs:
          command: push
          containerRegistry: $(dockerRegistryServiceConnection)
          repository: '$(imageName)'
          tags: |
            $(tag)
